### ISSUE TITLE
two options for your consideration. int if decmila == 0 and decimal only if >= n (1000)

### ISSUE THREAD

**Issue by jayenne** [Pharaonic/laravel-readable#1]
hi,
I have two thoughts...

*would you consider and option to not show the decimal if the decimal is 0 so 1.0 becomes 1
* would you also consider an option to only show decimals if >= 1000 i.e has an abreviated metric like K,M etc.

thanks.

**Comment by Pharaonic** [comment]
Hello,

> *would you consider and option to not show the decimal if the decimal is 0 so 1.0 becomes 1

You can use **ReadableDecInt** function.


> * would you also consider an option to only show decimals if >= 1000 i.e has an abbreviated metric like K,M etc.

Do you mean something like **ReadableHumanNumber** function but for decimals?  Is `>= 1000 decimals` == `>= 0.1` ?

If not just give me an example please.

**Comment by jayenne** [comment]
That's it. No decimals for >0.0 && <1000.0
